### ISSUE TITLE
Modul wird nicht angezeigt

### ISSUE THREAD

**Issue by MManu88** [fewieden/MMM-Fuel#27]
Ich habe das Modul wie in der Beschreibung steht installiert. 
Soweit so gut. Leider wird das Modul bei mir nicht angezeigt.
Den API Key habe ich angefordert und eingefügt. 
Die Koordinaten habe ich geändert.
Und die Position habe ich auf top_center geändert. Leider bleibt der Bildschirm in diesem Bereich einfach schwarz. Woran kann das liegen?

{
		    module: "MMM-Fuel",
		    position: "top_center",
		    config: {
			        api_key: "061c9d63-132b-6e62-9ee6-e6c4ae082b9d",
			        lat: 47.70223,
			        lng: 9.5678762,
			        types: ["diesel"],
 			}
		},

Grüße ebenfalls vom Bodensee

Manu

**Comment by fewieden** [comment]
I just used your config and I'm getting results for gas stations in Tettnang

**Comment by Jonathan214** [comment]
Hello, same problem here, i got this config:

{
		        module: "MMM-Fuel",
		        position: "bottom_right",
		        config: {
		            api_key: "d74db2a1-54af-9ef9-7eef-bb61c77a30b2",
		            lat: 53.050241,
		            lng: 8.646684499999992,
		            types: ["diesel"]
		        }
    		},

with the Key i got from "Tankerkoenig" and the Screen is black but I don't get any errors.
I installed "request". But not "npm" because this command is used for starting the mirror etc. with "npm start" so I thought it is already installed. Sorry I'm new. How do I install it if I have to do something for that too?

**Comment by fewieden** [comment]
@MManu88 that's because you downloaded the modul (github adds the branch name at the end, in this case master), if you clone it it has the right name.
