### ISSUE TITLE
Load Loop

### ISSUE THREAD

**Issue by Waynee91** [fewieden/MMM-Fuel#44]
Platform (Hardware/OS): Raspberry Pi with latest Raspian Stretch

Node version: 

MagicMirror version: 2.11.0

Module version: 2.1.0

Description of the issue: After installing the MMM-Fuel module and configuring this in the config.js file i got the problem that the prices will not be shown and i see only "Load".

My Configuration:
// Fuel        
        {
            module: "MMM-Fuel",
            position: "top_center",
            config: {
                provider: "spritpreisrechner",
                radius: "10",
                max: "5",
                lat: 47.630097,
                lng: 12.213639,
                types: ["e5"]
            }    
        },

Can anyone help me to solve this issue?

**Comment by Waynee91** [comment]
If i change the type to "diesel" it will work but i need the prices for e5

**Comment by fewieden** [comment]
Hi @Waynee91,

I can see 3 issues/improvements with your config:
1. Since you changed the fuel type, you also need to adjust sortBy. Please add `sortBy: "e5",` to your config.
2. You don't need to wrap quotes around numbers, this could actually result in issues with some modules.
3. If you do not differ from the default value you do not need to specify it in the config. Therefore you can remove the max property from your config.

**Comment by fewieden** [comment]
I also just released a new version that has a fallback if sortBy is misconfigured, so it doesn't get stuck in loading.
