### ISSUE TITLE
Zero € prise

### ISSUE THREAD

**Issue by lolobyte** [fewieden/MMM-Fuel#6]
In my search of available stations is one that didn't have the sort of E10 for sale.
The MMM-Module show me 0€ for the E10. ;-)

After my kommunikation with the tankerkoenig api-key  distibutor, is it not realy klear what we kann do.
Is it possible to check this issue in your SW?

The Station that i know without E10 is:

Tankstelle ED-Neckarsulm in 74172 Neckarsulm, Rötelstrasse 35

**Comment by fewieden** [comment]
Fixed with https://github.com/fewieden/MMM-Fuel/commit/2be05b8eb2ab68bfbee4a38ae8d11fcb71b34a18

if there is 1 fuel type present in config and thie price is 0€ the gas station gets completely removed from the display

if there is more than one fuel type in config and one of them has a price greater than 0€ the gas station will be displayed at the end of the list, otherwise the gas stations is also removed from the list
